### ISSUE TITLE
EXC_BREAKPOINT: queue = 'com.apple.root.user-initiated-qos.cooperative'

### ISSUE THREAD

**Issue by flyer135** [dixahq/ios-messenger#10]
When I called "Messenger.configure(config)" on app launching,  it crashed because of 'EXC_BREAKPOINT'. 
The detail log is as this:
* thread #4, queue = 'com.apple.root.user-initiated-qos.cooperative', stop reason = EXC_BREAKPOINT (code=1, subcode=0x10bcbba24)
  * frame #0: 0x000000010bcbba24 libdispatch.dylib`_dispatch_kevent_worker_thread + 2740
    frame #1: 0x00000001f114612c libsystem_pthread.dylib`_pthread_wqthread + 344

The run environment: 
Xcode 14.3(Debug)   iPhone Xs Max(iOS15.1)

Please help to fix it, Thanks.

**Comment by Nederby** [comment]
Hi @flyer135 

I can see this issue was reported some time ago. Is this still an issue, and if so, can you try with the newest version of the SDK?

Thanks in advance!

**Comment by Nederby** [comment]
Hi again @flyer135 

We are going to close this issue, but please open another if this is still something that you are experiencing.
