### ISSUE TITLE
CRASH: Symbol not found - iOS 15.7.9 - Exact steps to reproduce

### ISSUE THREAD

**Issue by MartinPrusa** [dixahq/ios-messenger#24]
Dear Dixa Developers,

My App is crashing after Dixa library is added to the project. It happens **since** Dixa version **1.6.1**. Dixa **version 1.6.0 works fine**. It does not matter if i use SPM or manual install.

Steps to reproduce:

1. Create new Xcode Project - Swift - Storyboard - iOS deployment target 15.6
2. Install DixaSDK with version 1.6.1 or higher - it does not matter if i use manual process or SPM
3. run it on device with iOS 15.7.9 (i use iPhone SE 1st Gen) - 15.7.9 is the latest iOS supported on iPhone SE 1st gen
4. app will install and crash

Xcode crash log:

```
dyld[2523]: Symbol not found: (_$s10Foundation10NSNotFoundSivg)
  Referenced from: '/private/var/containers/Bundle/Application/F83900E5-A1E9-4F86-90BC-7490D9683D7B/com.dixa.crashtest.app/Frameworks/DixaMessenger.framework/DixaMessenger'
  Expected in: '/System/Library/Frameworks/Foundation.framework/Foundation'
```

This crash appears only on iOS 15.x, since iOS 16+ the crash is not appearing.

Kind regards,
-Martin

**Comment by Nederby** [comment]
Hi Martin, 

Thanks for the thorough description of this issue. We can recreate the issue and are working on making the SDK support iOS `15.x` again. Hopefully, we have a new release ready by the end of this week or early next week.

Thanks for your patience.

**Comment by Nederby** [comment]
Hi again @MartinPrusa 

The release since [SDK version 1.6.5](https://github.com/dixahq/ios-messenger/releases/tag/1.6.5) again supports iOS 15.

Sorry for the inconvenience that this has caused.
