### ISSUE TITLE
SIGABRT: Attempted to read an unowned reference but the object was already deallocated

### ISSUE THREAD

**Issue by honghoangsts** [dixahq/ios-messenger#25]
Hi Dixa,

 I use version **1.5.2** for React Native app and Sentry gave me this alert. This issue only happens on iOS.
<img width="700" alt="image" src="https://github.com/dixahq/ios-messenger/assets/63329049/77b6db74-b4ce-4bfd-aba0-475695723967">

I try multiple versions **1.6.0 -> 1.6.5** but now these have issue with missing symbols so I can not use these latest versions.
<img width="250" alt="image" src="https://github.com/dixahq/ios-messenger/assets/63329049/87e95064-2b9a-4f38-a2ad-f2564d319348">

Device:
<img width="341" alt="image" src="https://github.com/dixahq/ios-messenger/assets/63329049/d00d99a2-63ea-440b-9b02-96fcde16f807">

Can you guys please help to fix it. Thanks

**Comment by SAleksiev** [comment]
Hello honghoangsts,
please try to use 1.6.7 as our latest release build. 

Regards,
Stefan
