### ISSUE TITLE
Kingfisher Signature Release Issue

### ISSUE THREAD

**Issue by Alex-Coetzee** [dixahq/ios-messenger#26]
Hey Devs :)

Currently getting builds revoked by Apple as the Kingfisher SDK dependency has no valid signature.

> Missing signature - Your app includes “Frameworks/DixaMessenger.framework/DixaMessenger”, which includes Kingfisher, an SDK that was identified in the documentation as a privacy-impacting third-party SDK. If a new app includes a privacy-impacting SDK, or an app update adds a new privacy-impacting SDK, the SDK must include a signature file. Please contact the provider of the SDK that includes this file to get an updated SDK version with a signature. For details about verifying the code signature for a third-party SDK

Any advice regarding / update on this would be appreciated.

**Comment by garriguv** [comment]
We encountered the same problem in our app.

Kingfisher has added a privacy manifest: https://github.com/onevcat/Kingfisher/commit/e60b41f47001e838d5672a2acd3fcbf3114bd8ba

**Comment by nebojsas** [comment]
We have the same problem, out deployments are blocked until this is resolved. We are using the latest release version (1.9.5)

Are there any updates on when will this issue be fixed?

**Comment by Nederby** [comment]
Hi @Alex-Coetzee, @nebojsas and @nebojsas 

Thanks for informing us about this: we removed the Kingfisher library from the latest iOS SDK release (`1.9.6` https://github.com/dixahq/ios-messenger/releases/tag/1.9.6).

Sorry for any hassle this might cause! Feel free to reach out if you need help or have any questions.
