### ISSUE TITLE
EXC_BREAKPOINT: DixaMessenger/ConversationViewController.swift:302: Fatal error: Failed getting message

### ISSUE THREAD

**Issue by hoangSTS** [dixahq/ios-messenger#5]
Sometimes the app crashed when attachment button pressed, please give me some advices.
iphone 13
iOS 16.2

**Comment by idortulov** [comment]
Can you please share a crash log?

**Comment by Celinder** [comment]
Hi @hoangSTS 👋 we are looking into this further but cannot seem to reproduce it. Are there any specific steps you take that could help us in the right direction?

**Comment by Nederby** [comment]
This should have been solved in a newer version of the SDK. If that is not the case, please add a new comment to this issue.
