### ISSUE TITLE
Layout constraint warnings

### ISSUE THREAD

**Issue by longnguyenba-oda** [dixahq/ios-messenger#7]
Hi, 
Showing the messenger on the iOS client prints out a bunch of layout constraint warnings:
`[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x6000025ec550 BaseUI/DixaLogo.height == 40   (active, names: BaseUI/DixaLogo:0x127f592f0 )>",
    "<NSLayoutConstraint:0x6000025ecc30 UIButton:0x136f71ef0.height == 56   (active)>",
    "<NSLayoutConstraint:0x6000025ed4f0 BaseUI/DixaLogo.top == UILayoutGuide:0x600003cfd340'UIViewLayoutMarginsGuide'.top + 16   (active, names: BaseUI/DixaLogo:0x127f592f0 )>",
    "<NSLayoutConstraint:0x6000025ec4b0 BaseUI/DixaLogo.centerY == UIButton:0x136f71ef0.centerY   (active, names: BaseUI/DixaLogo:0x127f592f0 )>",
    "<NSLayoutConstraint:0x6000025eccd0 UIButton:0x136f71ef0.top == UILayoutGuide:0x600003cfd340'UIViewLayoutMarginsGuide'.top + 16   (active)>"
)`
Thanks in advance! 🙏

**Comment by Celinder** [comment]
This should be fixed in 1.4.0+ please let us know if the problem persists.
