### ISSUE TITLE
Dixa SDK automatically asks for push notification permission even if app don't support push notification

### ISSUE THREAD

**Issue by longnguyenba-oda** [dixahq/ios-messenger#8]
As the title suggested, it would make more sense to declare the capabilities that the client will support and then decide if the SDK should ask for push notification permission.

![IMG_2357](https://user-images.githubusercontent.com/98813306/229825838-f74ee62c-d6f1-4904-a87c-bfbbb002c673.png)

**Comment by Celinder** [comment]
@longnguyenba-oda This will be resolved in the next release of the Dixa Messenger.
