### ISSUE TITLE
Wrong status bar tint color?

### ISSUE THREAD

**Issue by longnguyenba-oda** [dixahq/ios-messenger#9]
The black status bar tint color seems a bit off compared to the dark purple-ish background color. 
![IMG_2357](https://user-images.githubusercontent.com/98813306/229827389-73ebd97d-ce04-4082-b352-1106da6b63c5.png)

**Comment by Celinder** [comment]
👋  @longnguyenba-oda we'll try to address in an upcoming release. Thanks for flagging it.
